
all:
	cl  /WX /wd4820 /wd4668 /wd4710 /Od /Zi /Zo FoxitFuzz_Harness.cpp /MT -I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt" D:\libucrt.lib

clean:
	del FoxitFuzz_Harness.exe FoxitFuzz_Harness.exp FoxitFuzz_Harness.ilk FoxitFuzz_Harness.lib foxit10.FoxitFuzz_Harness FoxitFuzz_Harness.pdb vc140.pdb