
all:
	cl  /WX /wd4820 /wd4477 /wd4668 /wd4710 /Od /Zi /Zo foxit10.cpp /MT -I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22000.0\ucrt\x86\libucrt.lib"

clean:
	del foxit10.exe foxit10.exp foxit10.ilk foxit10.lib foxit10.obj foxit10.pdb vc140.pdb