
all:
	cl  /WX /wd4820 /wd4477 /wd4668 /wd4710 /Od /Zi /Zo foxit10.cpp /MT -I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt" D:\libucrt.lib

clean:
	del foxit10.exe foxit10.exp foxit10.ilk foxit10.lib foxit10.obj foxit10.pdb vc140.pdb